# Generated by Django 3.0.3 on 2020-07-27 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=30, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(blank=True, default=None, max_length=30, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(blank=True, default=None, max_length=30, verbose_name='Apellido Materno')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
